name: Steep

on:
  push:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, '3.0', 3.1]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec appraisal install
      - run: bundle exec rbs collection install
      - run: |
          bundle exec steep check | ruby -pe 'sub(/^(.+):(\d+):(\d+): (.+)$/, %q{::error file=\1,line=\2,col=\3::\4})'
        shell: bash
